[project]
name = "AoC"
version = "0.1.0"
description = "Advent Of Code - December tradition since 2015"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aocd>=0.1",
    "arrow>=1.3.0",
    "rich>=13.9.2",
    "ruff>=0.6.9",
]
